@startuml


loop true
    main --> MonitoringService: monitoringCanData()
        MonitoringService-->Parser: getCanData()
        Parser-->MonitoringService: id, length data
        alt 対象CANID
        MonitoringService ->> main: E_DataKind, data
        end

    alt 対象CANID
        main-->Sender: sendCanData()
        Sender-->main: 
    end
end

@enduml